apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: orders-allow-from-gateway
  namespace: prod
spec:
  podSelector:
    matchLabels:
      app: orders-service
      env: prod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
              env: prod
      ports:
        - protcol: TCP
          port: 8080
