apiVersion: v1
kind: Service
metadata:
  name: golang-aws-app
  namespace: default
  labels:
    app: golang-aws-app
spec:
  selector:
    app: golang-aws-app
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None
